name: Moloco Report

on:
  workflow_dispatch:
  schedule:
    # Runs at 10:00 AM SGT every day
    - cron: '0 2 * * *'

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    env:
      MOLOCO_EMAIL: ${{ secrets.MOLOCO_EMAIL }}
      MOLOCO_PASSWORD: ${{ secrets.MOLOCO_PASSWORD }}
      MOLOCO_CREATE_REPORT_URL: ${{ secrets.MOLOCO_CREATE_REPORT_URL }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Decode GCP Credentials
      run: |
        echo "${{ secrets.GCP_CREDENTIALS }}" | base64 -d > credentials.json

    - name: Run report generator
      run: python src/main.py
